#!/bin/bash

# Script to convert set of PNG images into mp4 video 
cd vids/ ;
for f in *ppm ; 
do convert -quality 100 $f `basename $f ppm`png; 
done ;
ffmpeg -framerate 30 -pattern_type glob -i '*.png' -c:v libx264 -r 30 -pix_fmt yuv420p out.mp4;
mv out.mp4 ../final.mp4; 
cd ..;
